"""Add responsive widths

Revision ID: 3691f1c5605e
Revises: a831bf33846a
Create Date: 2026-01-21 13:00:05.222336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3691f1c5605e'
down_revision = 'a831bf33846a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immo_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width_tablet', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('width_mobile', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immo_question', schema=None) as batch_op:
        batch_op.drop_column('width_mobile')
        batch_op.drop_column('width_tablet')

    # ### end Alembic commands ###
