"""Add Verein Anbaustelle Models

Revision ID: 5a0ecb6e1ffa
Revises: 6cff9328d71c
Create Date: 2026-02-03 13:02:50.227291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0ecb6e1ffa'
down_revision = '6cff9328d71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anbaustelle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('anbau_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('state_seat', sa.String(length=50), nullable=True),
    sa.Column('state_grow', sa.String(length=50), nullable=True),
    sa.Column('state_dist', sa.String(length=50), nullable=True),
    sa.Column('board_member', sa.String(length=150), nullable=True),
    sa.Column('prev_officer', sa.String(length=150), nullable=True),
    sa.Column('is_ev', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('anbaustelle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anbaustelle_id'], ['anbaustelle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ausgabestelle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('verein_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['verein_id'], ['verein.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verein_bereichsleitung',
    sa.Column('verein_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verein_id'], ['verein.id'], ),
    sa.PrimaryKeyConstraint('verein_id', 'user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verein_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_verein_id', 'verein', ['verein_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('verein_id')

    op.drop_table('verein_bereichsleitung')
    op.drop_table('ausgabestelle')
    op.drop_table('verein')
    op.drop_table('anbaustelle')
    # ### end Alembic commands ###
