"""onboarding und Bereichsleitung

Revision ID: 6cff9328d71c
Revises: 6b8724994b00
Create Date: 2026-01-27 18:46:45.463569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cff9328d71c'
down_revision = '6b8724994b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immo_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False, server_default='immo'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('onboarding_confirmed_at')

    with op.batch_alter_table('immo_section', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
