"""Add required and metadata flags to questions

Revision ID: 781c3d0dffae
Revises: 0b704af9680d
Create Date: 2026-01-19 21:32:16.008212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781c3d0dffae'
down_revision = '0b704af9680d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('immo_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_metadata', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immo_question', schema=None) as batch_op:
        batch_op.drop_column('is_metadata')
        batch_op.drop_column('is_required')

    op.drop_table('inspection_log')
    # ### end Alembic commands ###
