"""Add Mariana Stats

Revision ID: 99c6d229c938
Revises: e5f6dd0830f2
Create Date: 2026-01-22 22:38:04.599447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c6d229c938'
down_revision = 'e5f6dd0830f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mariana_applied', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mariana_approved', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mariana_rejected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mariana_withdrawn', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_stat', schema=None) as batch_op:
        batch_op.drop_column('mariana_withdrawn')
        batch_op.drop_column('mariana_rejected')
        batch_op.drop_column('mariana_approved')
        batch_op.drop_column('mariana_applied')

    # ### end Alembic commands ###
