"""Add is_print to ImmoQuestion

Revision ID: b4554371568b
Revises: 781c3d0dffae
Create Date: 2026-01-20 10:16:50.090343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4554371568b'
down_revision = '781c3d0dffae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immo_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_print', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immo_question', schema=None) as batch_op:
        batch_op.drop_column('is_print')

    # ### end Alembic commands ###
