"""Add MarketStat

Revision ID: e5f6dd0830f2
Revises: 3691f1c5605e
Create Date: 2026-01-22 20:58:03.398519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6dd0830f2'
down_revision = '3691f1c5605e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=True),
    sa.Column('applied', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('rejected', sa.Integer(), nullable=True),
    sa.Column('withdrawn', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.String(length=20), nullable=True),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_stat')
    # ### end Alembic commands ###
